"""empty message

Revision ID: 472e9798cb4d
Revises: 7a2f6511abeb
Create Date: 2020-07-26 15:35:19.051220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472e9798cb4d'
down_revision = '7a2f6511abeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
